# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HZAUSoilTexture
                                 A QGIS plugin
 使用砂粒和黏粒栅格数据生成土壤质地图
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-03-14
        copyright            : (C) 2023 by 邓阳
        email                : dengyang.chn@foxmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load HZAUSoilTexture class from file HZAUSoilTexture.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .hzau_soil_texture import HZAUSoilTexture
    return HZAUSoilTexture(iface)
